version: '3.4'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'

  rest-api-node:
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: on-failure